@startuml
 !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

 title C4 Context Diagram for Heating Home Monolith

 Person(webUser, "Web User", "Web User of the smart home")
 Person(mobileUser, "Mobile User", "Mobile user of the smart home")

 System_Ext(sensor, "Sensor", "Temperature sensor in home")

 System(HeatingHomeMonolith, "Heating Home Monolith", "[Java Spring + Postgres] Fetches data from devices and monitors temperature in smart home", "hvhv")
 

 Rel(webUser, HeatingHomeMonolith, "Uses")
 Rel(mobileUser, HeatingHomeMonolith, "Uses")
 Rel(HeatingHomeMonolith, sensor, "Fetches data")
@enduml