@startuml
title Микросервисный backend

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(smartHomeSystem, "SmartHome System Backend") {
  Container(backend,  "Микросервисное приложение", "Java, Spring boot", "Handles user interactions")
  Container(database, "База данных", "PostgreSQL", "Хранение данных")
  Container(cache, "Кэш", "Redis", "Хранение кэша")
  Container(broker, "Брокер сообщений", "Apache Kafka", "Обмен сообщениями между микросервисами")
}

Container(backend, "Микросервисное приложение", "Java, Spring boot") {
  Component(APIGateway, "APIGateway", "Проксирует запросы от клиентов, балансирует нагрузку, управляет авторизацией и ролями")
  Component(SensorService, "SensorService", "Управляет датчиками")
  Component(DeviceService, "DeviceService", "Управляет устройствами")
  Component(ProfileService, "ProfileService", "Управляет профилем пользователя")
  Component(ScenarioService, "ScenarioService", "Управляет сценариями умного дома")
  Component(NotificationService, "NotificationService", "Управляет оповещениями пользователей")
  Component(AuditService, "AuditService", "Собирает и агрегирует данные для аналитики")
}

Rel(APIGateway, SensorService, "CRUD запросы по датчикам")
Rel(APIGateway, DeviceService, "CRUD запросы по устройствам")
Rel(APIGateway, ProfileService, "CRUD запросы по профилю пользователя")
Rel(APIGateway, ScenarioService, "CRUD запросы по пользовательским сценариям умного дома")
Rel(APIGateway, NotificationService, "Запросы по оповещениям")
Rel(APIGateway, AuditService, "Формирование и выгрузка аналитических отчётов")


Container(database, "База данных", "PostgreSQL", "Хранение данных") {
  Component(SensorServiceDatabase, "SensorServiceDatabase", "Хранит данные о датчиках и их показаниях")
  Component(DeviceServiceDatabase, "DeviceServiceDatabase", "Хранит данные об устройствах")
  Component(ProfileServiceDatabase, "ProfileServiceDatabase", "Хранит данные о пользователях")
  Component(ScenarioServiceDatabase, "ScenarioServiceDatabase", "Хранит пользовательские сценарии")
  Component(NotificationServiceDatabase, "NotificationServiceDatabase", "Хранит данные о каналах оповещения")
  Component(AuditServiceDatabase, "AuditServiceDatabase", "Хранит данные для аналитики")
}

Container(cache, "Кэш", "Redis", "Хранение кэша") {
  Component(APIGatewayDatabase, "APIGatewayDatabase", "Храненение кэша для частых и трудозатратных запросов")
}

Rel(APIGateway, cache, "Чтение, запись, инвалидация кэша")
Rel(SensorService, SensorServiceDatabase, "Чтение и запись")
Rel(DeviceService, DeviceServiceDatabase, "Чтение и запись")
Rel(ProfileService, ProfileServiceDatabase, "Чтение и запись")
Rel(ScenarioService, ScenarioServiceDatabase, "Чтение и запись")
Rel(NotificationService, NotificationServiceDatabase, "Чтение и запись")
Rel(AuditService, AuditServiceDatabase, "Чтение и запись")

Container(broker, "Брокер сообщений", "Apache Kafka") {
  Component(kafka, "Apache Kafka", "Управление сообщениями, балансировка")
}

Rel(SensorService, kafka, "Чтение и публикация")
Rel(DeviceService, kafka, "Чтение и публикация")
Rel(ProfileService, kafka, "Чтение и публикация")
Rel(ScenarioService, kafka, "Чтение и публикация")
Rel(NotificationService, kafka, "Чтение")
Rel(AuditService, kafka, "Чтение и публикация")

System_Ext(sensor, "Датчики", "Датчики температуры")
System_Ext(device, "Устройства", "Управление отоплением")

Rel(SensorService, sensor, "Получает данные")
Rel(DeviceService, device, "Отправляет команды")

@enduml